version: "2.1"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: taskList
    volumes:
      - './data:/data/db'
    ports:
      - 27017:27017
